### ISSUE TITLE
The deployment is currently unavailable

### ISSUE THREAD

**Issue by Smile4ever** [mrmartineau/xkcd-api#1]
When navigating to https://xkcd.now.sh/
![image](https://user-images.githubusercontent.com/544411/39088927-8474d2bc-45bb-11e8-951d-ffa79b45178a.png)

Is this something you plan to fix?

**Comment by Smile4ever** [comment]
In the meantime, I have made https://xkcdapi.now.sh available.

**Comment by mrmartineau** [comment]
@Smile4ever thanks, I will get it up and running soon

**Comment by Smile4ever** [comment]
@mrmartineau Zeit Now 1.0 is closing, they are replacing it with Vercel Now 2.0. It just requires a little change (see my repository). Are you still planning to get your copy uploaded again?
