### ISSUE TITLE
Archive support?

### ISSUE THREAD

**Issue by dasmikko** [mrmartineau/xkcd-api#2]

**Comment by mrmartineau** [comment]
@dasmikko can you provide more information please?

**Comment by dasmikko** [comment]
Oh Yeah sure.

I was hoping to have a json version of the archive page.

Mainly just a list of all the items, with name and id.

**Comment by mrmartineau** [comment]
@dasmikko which archive page?

**Comment by dasmikko** [comment]
This page:
https://xkcd.com/archive/

**Comment by mrmartineau** [comment]
@dasmikko if it is available to me from their API, I could add it, but I'm pretty sure that it isn't there.. 👎
