### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by lloydjatkinson** [mrmartineau/xkcd-api#3]
Hi,

The API does not seem to be working. I am getting a 500 when I try call the API.

![image](https://user-images.githubusercontent.com/5633938/48874742-a91b3f00-edec-11e8-9ae2-69b045a5d143.png)

**Comment by timjklein36** [comment]
@lloydjatkinson You don't need to specify the `info.0.json` path. Simplify your HTTP call to just `https://xkcd.now.sh`.
