### ISSUE TITLE
"The deployment could not be found"

### ISSUE THREAD

**Issue by hugovk** [mrmartineau/xkcd-api#5]
https://xkcd.now.sh/ says "The deployment could not be found on ZEIT Now".

![image](https://user-images.githubusercontent.com/1324225/63165979-b260d180-c035-11e9-87a7-a8be01ebd888.png)

Thanks for the API! Any chance to revive it?

**Comment by Smile4ever** [comment]
Please see #1 
I host a mirror on https://xkcdapi.now.sh with the code of 21 Apr 2018 (currently the last revision).

**Comment by hugovk** [comment]
Great, thank you!

**Comment by hugovk** [comment]
Closing, https://xkcd.now.sh/ is now available! 🚀
