### ISSUE TITLE
README doesn't match actual API of xkcd.now.sh

### ISSUE THREAD

**Issue by mrdrogdrog** [mrmartineau/xkcd-api#7]
Your README says "use https://xkcd.now.sh/1000". But this results in an 404 error, but it should work according to the code. 

However the deployed version has another syntax. E.g. for 1000 it's https://xkcd.vercel.app/?comic=1000.
Maybe an old version?

**Comment by mrmartineau** [comment]
hi @mrdrogdrog, this is quite an old project and Vercel changed their url scheme since I first published it. I think xkcd.vercel.app is run by someone else actually..
